[general]
import = ["themes/iceberg.toml"]
live_config_reload = true

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-i", "-c", "unset HERDR_ENV HERDR_SOCKET_PATH HERDR_WORKSPACE_ID HERDR_TAB_ID HERDR_PANE_ID; exec herdr"] }

[window]
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "Both"
padding = { x = 12, y = 12 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 10.5

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true, mods = "Command" }
binding = { key = "O", mods = "Control|Shift" }
regex = '(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>"\s{-}\^⟨⟩`\\]+'

[[keyboard.bindings]]
key = "Enter"
mods = "Command"
action = "ToggleMaximized"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "/"
mods = "Command"
action = "SearchForward"

[[keyboard.bindings]]
key = "="
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Command"
action = "DecreaseFontSize"
